version: '3'

services:
  app:
    build:
      context: ./app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks:
      - nodenet
    volumes:
      - ./app:/app
      - /app/node_modules
    tty: true
    ports:
      - '4000:4000'

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
    networks:
      - nodenet

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '8080:80'
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge
